[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
clap = "2.33"
tabular = "0.1.4"
users = "0.11"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
