[package]
name = "catr"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"

[dependencies]
anyhow = "1.0.95"
clap = "2.33"
pretty_assertions = "1.4.1"
